services:
  web-app-playground-db:
    image: postgres:18-alpine
    container_name: web-app-playground-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WebAppPlaygroundDb
    ports:
      - "5434:5432"
    volumes:
      - postgres_web_app_playground_db:/var/lib/postgresql

  web-app-playground-queue:
    image: rabbitmq:4.2.3-management
    container_name: web-app-playground-queue
    restart: unless-stopped
    ports:
      - "5672:5672" # Port for the AMQP protocol
      - "15672:15672" # Port for the management plugin UI

volumes:
  postgres_web_app_playground_db:
