// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAppPlayground.Data;

#nullable disable

namespace WebAppPlayground.Data.Migrations
{
    [DbContext(typeof(JsonOwnedContext))]
    [Migration("20260124130654_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAppPlayground.Data.JsonOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_json_owners");

                    b.ToTable("json_owners", (string)null);
                });

            modelBuilder.Entity("WebAppPlayground.Data.JsonOwner", b =>
                {
                    b.OwnsOne("WebAppPlayground.Data.JsonDetails", "Details", b1 =>
                        {
                            b1.Property<int>("JsonOwnerId");

                            b1.Property<string>("Name");

                            b1.HasKey("JsonOwnerId");

                            b1.ToTable("json_owners");

                            b1
                                .ToJson("details")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("JsonOwnerId")
                                .HasConstraintName("fk_json_owners_json_owners_id");

                            b1.OwnsMany("WebAppPlayground.Data.JsonSubDetail", "SubDetails", b2 =>
                                {
                                    b2.Property<int>("JsonDetailsJsonOwnerId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Value");

                                    b2.HasKey("JsonDetailsJsonOwnerId", "__synthesizedOrdinal")
                                        .HasName("pk_json_owners");

                                    b2.ToTable("json_owners");

                                    b2.WithOwner()
                                        .HasForeignKey("JsonDetailsJsonOwnerId")
                                        .HasConstraintName("fk_json_owners_json_owners_json_details_json_owner_id");
                                });

                            b1.Navigation("SubDetails");
                        });

                    b.Navigation("Details")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
