namespace CsharpPlayground.OOP;

public class Person(string firstName) : IEquatable<Person>
{
    // Compile-time constant fields (implicitly static)
    // Kotlin: const val stringConst: String = "This is a constant string"
    public const string StringConst = "This is a constant string";
    public const int IntConst = 42;
    public const decimal DecimalConst = 4.2m;
    public const bool BoolConst = true;

    // Static read-only field
    // Kotlin: companion object { val names: List<String> = listOf("Kotlin", "Java", "C#", "Python") }
    public static readonly IReadOnlyList<string> Names = ["Kotlin", "Java", "C#", "Python"];

    // Static mutable field
    // Kotlin: companion object { var count: Int = 0 }
    private static int _count = 0;

    // Static method to increment _count
    public static void IncrementCount()
    {
        _count++;
        Console.WriteLine($"Count incremented to {_count}");
    }

    // Readonly instance field
    // Kotlin: private val salary: Double = 1000.0
    private readonly double _salary = 1000.0;

    // Read-only auto-implemented properties (with backing fields generated by compiler)
    // Kotlin: val firstName: String = firstName
    public string FirstName { get; } = firstName;

    // Read-only auto-implemented properties (with backing fields generated by compiler)
    // and required modifier
    // Kotlin: val lastName: String and initialized in constructor
    public required string LastName { get; init; }

    // Init-only auto-implemented property (with backing field)
    // Kotlin: val address: String? and initialized in constructor
    public string? Address { get; init; }

    // Mutable auto-implemented property (with backing field)
    // Kotlin: var age: Int
    public int Age { get; set; }

    // Computed property
    public string FullName => $"{FirstName} {LastName}";
    public bool IsAdult => Age >= 18;

    public override string ToString()
    {
        return
            $"{nameof(FirstName)}: {FirstName}, " +
            $"{nameof(LastName)}: {LastName}, " +
            $"{nameof(Address)}: {Address}, " +
            $"{nameof(Age)}: {Age}, " +
            $"{nameof(FullName)}: {FullName}," +
            $" {nameof(IsAdult)}: {IsAdult}, " +
            $"{nameof(_salary)}: {_salary}";
    }

    // From IEquatable<Person>
    public bool Equals(Person? other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;
        return string.Equals(FirstName, other.FirstName, StringComparison.Ordinal)
               && string.Equals(LastName, other.LastName, StringComparison.Ordinal)
               && string.Equals(Address, other.Address, StringComparison.Ordinal)
               && Age == other.Age;
    }

    // From Object
    public override bool Equals(object? obj)
    {
        if (obj is null) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((Person)obj);
    }

    // static `Equals` similar to Java `Objects.equals(a, b)`
    public static bool operator ==(Person? left, Person? right) => Equals(left, right);
    public static bool operator !=(Person? left, Person? right) => !Equals(left, right);

    public override int GetHashCode() => HashCode.Combine(FirstName, LastName, Address, Age);
}